---
version: "2.0"
services:
  chatbot:
    image: chicha21/story_maker:1.0
    expose:
      - port: 8000
        as: 8000
        to:
          - global: true
    env:
      - PORT=5000
profiles:
  compute:
    chatbot:
      resources:
        cpu:
          units: 1
        memory:
          size: 2Gi
        storage:
          - size: 5Gi
  placement:
    dcloud:
      pricing:
        chatbot:
          denom: uakt
          amount: 1000
deployment:
  chatbot:
    dcloud:
      profile: chatbot
      count: 1
